---
- name: configure iptables
  hosts: all
  become: true

  vars_files: [secrets/ipset.yml]

  pre_tasks:
  
    - name: disable ufw
      service:
        name: ufw
        enabled: false
        state: stopped

  
  tasks:
  
    - name: install pacakges package
      apt: 
        pkg: "{{item}}"
        state: present
      loop:
        - iptables-persistent
        - ipset
      
    - name: copy ipables config
      synchronize:
        src: assets/iptables
        dest: /etc/iptables

    - name: add ssh ips to ipset
      lineinfile:
        path: /etc/iptables/ipset
        regexp: "add ssh {{item}}"
        line: "add ssh {{item}}"
      loop: "{{ ssh }}"

    - name: add swarm ips to ipset
      lineinfile:
        path: /etc/iptables/ipset
        regexp: "add swarm {{item}}"
        line: "add swarm {{item}}"
      loop: "{{ swarm }}"
    
    - name: create persisten ipset service
      copy: 
        src: assets/ipset-persistent.service
        dest: /etc/systemd/system/ipset-persistent.service
        owner: root
        group: root
        mode: 0644

    - name: reload daemon
      systemd:
        daemon_reload: yes

    - name: enable services
      service:
        name: "{{item}}"
        enabled: yes
      loop:
        - netfilter-persistent
        - ipset-persistent

    - name: load ipsets
      shell: ipset -exist restore -file /etc/iptables/ipset

    - name: load ipv4 rules
      shell: iptables-restore < /etc/iptables/rules.v4

    - name: load ipv6 rules
      shell: ip6tables-restore < /etc/iptables/rules.v6